name: Default
loss:
    name: ???
    xi: [-1, -0.75, -0.5, -0.25, 0, 0.25, 0.5, 0.75]
dataset: ???
training:
    lr: [1.0e-1, 1.0e-3, 1.0e-5]
    regularization: [1.0e-1, 1.0e-3, 1.0e-5]
    max_epochs: 3000
    batch_size: 256
    tol: 1.0e-4
evaluation:
    n_cv: 5
    test_ratio: 0.2
seed: -1
verbose: false
hydra:
    run:
        dir: "hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}"
